version: "3"

services:
  application:
    image: springmvc-app
    container_name: springmvc-app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - springmvc-db-net

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: bookcrud
    networks:
      - springmvc-db-net
    volumes:
      - /data/mysql:/var/lib/mysql

networks:
  springmvc-db-net:
